import type { Capability } from './types';

/*
==================================================
  SLAYER TERMINAL - THE CAPABILITY MAP
  (providers/capabilities.ts)

  provider → plan → data → the surface it feeds.
==================================================

  THIS FILE IS THE PRODUCT MAP, not documentation of one. Every surface in
  the terminal is fed by a simulator today; this says which real capability
  each one is WAITING for, so the swap is a lookup rather than an
  archaeology dig, and so the settings page can answer the only question a
  reader paying for four plans actually has: what am I getting.

  WHERE THE ROUTES CAME FROM. Not from memory, and not from a model's
  recollection of an API — both vendors publish machine-readable catalogs,
  and these were generated from them:

    Unusual Whales   unusual-whales/unusual-whales-official-mcp,
                     docs/endpoints.json — UW's own catalog, CI-verified
                     against their live API. 194 routes across 29 groups.
    Polygon/Massive  polygon-io/client-js, src/openapi.json — the complete
                     REST OpenAPI spec, re-synced from api.massive.com daily
                     by a bot. Plus polygon-io/client-python,
                     .massive/websocket.json for the socket channels.

  Both vendors' own domains are unreachable from this environment; their
  GitHub-published specs are not, and a spec the vendor generates is a
  better source than a docs page anyway. Anything neither spec stated is
  ABSENT here rather than guessed — a wrong field name costs more than a
  missing capability.

  THE CAVEATS ARE LOAD-BEARING. `greeks` and `implied_volatility` on a
  Polygon option snapshot are NOT in the schema's required set, so a client
  that assumes them crashes on the first deep-ITM contract. UW returns
  greek-exposure and spot-exposure in different units. Those belong beside
  the promise, at the same size, because a reader deciding whether to trust
  a number needs them at the same moment.
*/

export const CAPABILITIES: Capability[] = [
  // ── POLYGON / MASSIVE ─────────────────────────────────────────────────
  // api.massive.com — the polygon.io host remains supported. Auth is the
  // `apiKey` query param or an `Authorization: Bearer` header.
  {
    id: 'poly_stock_aggs',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'rest',
    market: 'stocks',
    endpoint: '/v2/aggs/ticker/{ticker}/range/{mult}/{span}/{from}/{to}',
    what: 'OHLCV bars at any timespan, second through year, twenty years back',
    feeds: ['candles'],
    surfaces: ['/weigher', '/pulse', '/paper', '/record/stocks'],
    caveat: 'limit maxes at 50,000 and defaults to 5,000 — stated only in the spec description, not the schema',
  },
  {
    id: 'poly_stock_snapshot',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'rest',
    market: 'stocks',
    endpoint: '/v2/snapshot/locale/us/markets/stocks/tickers',
    what: 'Every US ticker at once — day bar, previous day, last quote and last trade',
    feeds: ['tape'],
    surfaces: ['/pulse', '/weigher', '/record/stocks'],
    caveat: 'this envelope has no `results` key — the payload is under `tickers`',
  },
  {
    id: 'poly_stock_movers',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'rest',
    market: 'stocks',
    endpoint: '/v2/snapshot/locale/us/markets/stocks/{gainers|losers}',
    what: "The session's biggest movers, both directions",
    feeds: ['tape'],
    surfaces: ['/pulse', '/weigher'],
  },
  {
    id: 'poly_stock_trades',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'rest',
    market: 'stocks',
    endpoint: '/v3/trades/{ticker} · /v3/quotes/{ticker} · /v2/last/trade · /v2/last/nbbo',
    what: 'Tick-level trades and NBBO quotes, historical and last',
    feeds: ['tape'],
    surfaces: ['/trace/live-tape', '/paper'],
  },
  {
    id: 'poly_opt_chain_snapshot',
    provider: 'polygon',
    plan: 'Options Advanced',
    transport: 'rest',
    market: 'options',
    endpoint: '/v3/snapshot/options/{underlying}',
    what: 'The whole chain: quote, day bar, open interest, break-even, greeks and IV per contract',
    feeds: ['chain', 'exposure'],
    surfaces: ['/weigher', '/compass', '/pinpoint', '/terrain', '/paper'],
    caveat: 'greeks and implied_volatility are NOT required fields — absent on some contracts. There is no rho: delta, gamma, theta, vega only. limit defaults to 10, maxes at 250, so the chain must be paged',
  },
  {
    id: 'poly_opt_contracts',
    provider: 'polygon',
    plan: 'Options Advanced',
    transport: 'rest',
    market: 'options',
    endpoint: '/v3/reference/options/contracts',
    what: 'Contract reference — strikes, expiries, exercise style, shares per contract',
    feeds: ['chain'],
    surfaces: ['/weigher', '/compass', '/paper'],
  },
  {
    id: 'poly_opt_trades',
    provider: 'polygon',
    plan: 'Options Advanced',
    transport: 'rest',
    market: 'options',
    endpoint: '/v3/trades/{optionsTicker} · /v3/quotes/{optionsTicker}',
    what: 'Option prints and quotes at tick level',
    feeds: ['prints'],
    surfaces: ['/trace/live-tape', '/trace/odte'],
  },
  {
    id: 'poly_indices',
    provider: 'polygon',
    plan: 'Indices Advanced',
    transport: 'rest',
    market: 'indices',
    endpoint: '/v3/snapshot/indices · /v2/aggs/ticker/I:{index}/range/…',
    what: 'Index values and bars — SPX, NDX, VIX, DJI',
    feeds: ['candles'],
    surfaces: ['/pulse', '/terrain', '/pinpoint'],
    caveat: 'indices have no trades and no quotes — value and aggregates only, on both REST and socket',
  },
  {
    id: 'poly_indicators',
    provider: 'polygon',
    plan: 'Stocks / Options / Indices Advanced',
    transport: 'rest',
    market: 'any',
    endpoint: '/v1/indicators/{sma|ema|rsi|macd}/{ticker}',
    what: 'Server-computed SMA, EMA, RSI and MACD on any asset class',
    feeds: ['candles'],
    surfaces: ['/weigher', '/pulse', '/paper'],
    caveat: 'no `second` timespan here, unlike aggregates. MACD takes short/long/signal windows, not `window`',
  },
  {
    id: 'poly_reference',
    provider: 'polygon',
    plan: 'any paid plan',
    transport: 'rest',
    market: 'any',
    endpoint: '/v3/reference/tickers · /v2/reference/news · /v1/marketstatus/* · splits · dividends',
    what: 'Ticker details and branding, news with sentiment, market status and holidays, corporate actions',
    feeds: ['macro'],
    surfaces: ['/record/news', '/record/stocks', '/pulse'],
    caveat: 'reference endpoints carry no market entitlement at all — any paid plan reaches them',
  },
  {
    id: 'poly_financials',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'rest',
    market: 'stocks',
    endpoint: '/stocks/financials/v1/{income-statements|balance-sheets|cash-flow-statements|ratios}',
    what: 'Flat, typed financial statements and 24 valuation ratios — every ratio is also a filter',
    feeds: [],
    surfaces: ['/record/stocks', '/weigher'],
    caveat: 'these next-generation paths declare no entitlement in the spec — test against the key before relying on them',
  },
  {
    id: 'poly_fx_crypto',
    provider: 'polygon',
    plan: 'Currencies Starter',
    transport: 'rest',
    market: 'fx',
    endpoint: '/v2/aggs/ticker/C:{pair} · /v1/conversion · /v3/trades/X:{pair}',
    what: 'Forex and crypto bars, conversion, crypto trades — ten years back',
    feeds: [],
    surfaces: ['/pulse'],
    caveat: 'REST spells a pair C:EURUSD / X:BTCUSD; the socket spells the same pair USD/EUR and BTC-USD. Normalise or get silent empties',
  },
  {
    id: 'poly_ws_stocks',
    provider: 'polygon',
    plan: 'Stocks Advanced',
    transport: 'ws',
    market: 'stocks',
    endpoint: 'wss://socket.massive.com/stocks · T, Q, A, AM, LULD',
    what: 'Live trades, quotes, per-second and per-minute bars, limit-up/limit-down',
    feeds: ['tape', 'candles'],
    surfaces: ['/pulse', '/paper', '/weigher', '/trace/live-tape'],
    caveat: 'every frame is an ARRAY of messages, and status frames interleave with data',
  },
  {
    id: 'poly_ws_options',
    provider: 'polygon',
    plan: 'Options Advanced',
    transport: 'ws',
    market: 'options',
    endpoint: 'wss://socket.massive.com/options · T, Q, A, AM',
    what: 'Live option prints and quotes across the whole market',
    feeds: ['prints'],
    surfaces: ['/trace/live-tape', '/trace/odte', '/paper'],
  },
  {
    id: 'poly_ws_indices',
    provider: 'polygon',
    plan: 'Indices Advanced',
    transport: 'ws',
    market: 'indices',
    endpoint: 'wss://socket.massive.com/indices · V, A, AM',
    what: 'Live index values and bars',
    feeds: ['candles'],
    surfaces: ['/terrain', '/pinpoint', '/pulse'],
    caveat: 'the V channel keys its symbol as `T`, not `sym`, unlike every other channel',
  },
  {
    id: 'poly_ws_imbalance',
    provider: 'polygon',
    plan: 'NYSE Order Imbalances',
    transport: 'ws',
    market: 'stocks',
    endpoint: 'wss://socket.massive.com/stocks · NOI',
    what: 'Auction imbalances — imbalance and paired quantity, book clearing price, auction type',
    feeds: ['tape'],
    surfaces: ['/pulse', '/record/stocks'],
    caveat: 'socket only — there is no REST endpoint and no history, so anything you want to keep must be captured live',
  },

  // ── UNUSUAL WHALES ────────────────────────────────────────────────────
  // api.unusualwhales.com, Authorization: Bearer. Every route is a GET and
  // every response is wrapped in { data: … }. Array params take a [] suffix
  // on the wire — miss that and the filter silently returns everything.
  {
    id: "uw_stock",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "options",
    endpoint: "52 routes · /api/stock/{ticker}/info",
    what: "Chain, greeks and dealer exposure per ticker — 52 routes, including spot exposures per minute",
    feeds: ["chain","exposure"],
    surfaces: ["/weigher","/pinpoint","/terrain","/compass"],
  },
  {
    id: "uw_options",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "options",
    endpoint: "4 routes · /api/option-contract/{id}/flow",
    what: "One contract: its flow, its history, its intraday tape and its volume profile",
    feeds: ["chain"],
    surfaces: ["/weigher","/compass","/trace/tracker"],
  },
  {
    id: "uw_flow",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "options",
    endpoint: "13 routes · /api/option-trades/flow-alerts",
    what: "The options tape — every trade, flow alerts, multi-leg, exchange breakdown",
    feeds: ["prints","tape"],
    surfaces: ["/trace/live-tape","/trace/net-flow","/trace/odte","/trace/multi-leg"],
  },
  {
    id: "uw_market",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "17 routes · /api/market/market-tide",
    what: "Market tide, sector tide, total option volume, economic and FDA calendars",
    feeds: ["tape","macro"],
    surfaces: ["/pulse","/trace/net-flow"],
  },
  {
    id: "uw_darkpool",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "options",
    endpoint: "3 routes · /api/darkpool/recent",
    what: "Dark pool prints by ticker, recent, and the price levels they concentrate at",
    feeds: ["prints"],
    surfaces: ["/trace/dark-pool"],
  },
  {
    id: "uw_congress",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "4 routes · /api/congress/recent-trades",
    what: "Congressional trades, late reports, and who traded what",
    feeds: [],
    surfaces: ["/record/congress"],
  },
  {
    id: "uw_insider",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "4 routes · /api/insider/transactions",
    what: "Insider transactions with officer and director flags, by sector and by ticker",
    feeds: [],
    surfaces: ["/record/insiders"],
  },
  {
    id: "uw_institutions",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "7 routes · /api/institutions",
    what: "13F holdings, activity, sector weights and per-ticker ownership",
    feeds: [],
    surfaces: ["/record/stocks"],
  },
  {
    id: "uw_earnings",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "3 routes · /api/earnings/premarket",
    what: "Premarket and afterhours earnings with expected and realised moves",
    feeds: ["earnings"],
    surfaces: ["/record/earnings"],
  },
  {
    id: "uw_etf",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "5 routes · /api/etfs/{ticker}/info",
    what: "ETF holdings, exposure, country and sector weights, in and out flow",
    feeds: [],
    surfaces: ["/record/stocks","/weigher"],
  },
  {
    id: "uw_screener",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "options",
    endpoint: "4 routes · /api/screener/stocks",
    what: "Stock, option-contract and analyst screeners — around a hundred filters each",
    feeds: ["chain"],
    surfaces: ["/weigher","/trace/screener"],
  },
  {
    id: "uw_shorts",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "7 routes · /api/shorts/{ticker}/data",
    what: "Short interest, float, failures to deliver, volume by exchange",
    feeds: [],
    surfaces: ["/record/stocks"],
  },
  {
    id: "uw_seasonality",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "4 routes · /api/seasonality/market",
    what: "Monthly and per-year seasonal performance, by ticker and market-wide",
    feeds: [],
    surfaces: ["/record/stocks"],
  },
  {
    id: "uw_news",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "1 route · /api/news/headlines",
    what: "Headlines with tickers, tags and sentiment",
    feeds: [],
    surfaces: ["/record/news"],
  },
  {
    id: "uw_alerts",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "4 routes · /api/alerts",
    what: "The reader's own alert configurations and their firings",
    feeds: [],
    surfaces: ["/alerts"],
  },
  {
    id: "uw_politicians",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "5 routes · /api/politician-portfolios/people",
    what: "Politician portfolios, disclosures and per-ticker holders",
    feeds: [],
    surfaces: ["/record/congress"],
  },
  {
    id: "uw_unusual_trades",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "4 routes · /api/congress/unusual-trades",
    what: "Unusual congressional trading with chart data and stats",
    feeds: ["prints"],
    surfaces: ["/trace/live-tape"],
  },
  {
    id: "uw_private_markets",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "9 routes · /api/private-markets/companies",
    what: "Private market listings and activity",
    feeds: [],
    surfaces: [],
  },
  {
    id: "uw_companies_extras",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "5 routes · /api/companies/{ticker}/profile",
    what: "Company profile, dividends, splits, earnings estimates, call transcripts",
    feeds: [],
    surfaces: ["/record/stocks"],
  },
  {
    id: "uw_macro",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "2 routes · /api/commodities/{name}",
    what: "Commodities and economic indicators",
    feeds: ["macro"],
    surfaces: ["/pulse","/record/news"],
  },
  {
    id: "uw_forex",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "fx",
    endpoint: "3 routes · /api/forex/rate",
    what: "Forex rates, intraday and history",
    feeds: [],
    surfaces: ["/pulse"],
  },
  {
    id: "uw_digital_currencies",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "crypto",
    endpoint: "2 routes · /api/digital-currencies/intraday",
    what: "Digital currency intraday and history",
    feeds: [],
    surfaces: ["/pulse"],
  },
  {
    id: "uw_intel",
    provider: 'unusualwhales',
    plan: "API Advanced",
    transport: 'rest',
    market: "any",
    endpoint: "5 routes · /api/market/movers",
    what: "Top movers, IPO calendar, company listings, windowed and sliding analytics",
    feeds: [],
    surfaces: ["/pulse","/record/news"],
  },
  {
    id: "uw_crypto",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "crypto",
    endpoint: "4 routes · /api/crypto/{pair}/state",
    what: "Crypto state, OHLC candles and whale transactions",
    feeds: [],
    surfaces: ["/pulse"],
  },
  {
    id: "uw_fundamentals",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "6 routes · /api/stock/{ticker}/fundamental-breakdown",
    what: "Income statements, balance sheets, cash flows, earnings",
    feeds: [],
    surfaces: ["/record/stocks","/weigher"],
  },
  {
    id: "uw_technicals",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "1 route · /api/stock/{ticker}/technical-indicator/{function}",
    what: "Technical indicators per ticker",
    feeds: ["candles"],
    surfaces: ["/weigher","/pulse"],
  },
  {
    id: "uw_predictions",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "9 routes · /api/predictions/unusual",
    what: "Prediction-market data",
    feeds: [],
    surfaces: [],
  },
  {
    id: "uw_potus",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "any",
    endpoint: "2 routes · /api/potus/posts",
    what: "POTUS posts and schedule",
    feeds: [],
    surfaces: ["/record/news"],
  },
  {
    id: "uw_futures",
    provider: 'unusualwhales',
    plan: "API",
    transport: 'rest',
    market: "futures",
    endpoint: "5 routes · /api/futures/contracts",
    what: "CME futures — active contracts, live flow, trades, candles, settlement and open interest",
    feeds: ["candles","tape"],
    surfaces: ["/paper","/pulse"],
  },
  {
    id: 'uw_ws',
    provider: 'unusualwhales',
    plan: 'API Advanced',
    transport: 'ws',
    market: 'options',
    endpoint: 'wss://api.unusualwhales.com/socket · option_trades, flow-alerts, gex:*, gex_strike:*, gex_strike_expiry:*, price:*, news, lit_trades, off_lit_trades, periscope',
    what: 'Live option trades, flow alerts, per-strike dealer exposure, dark pool prints, and the SPX periscope',
    feeds: ['prints', 'exposure', 'tape'],
    surfaces: ['/trace/live-tape', '/terrain', '/pinpoint', '/trace/dark-pool'],
    caveat: 'the token rides in the query string, frames arrive as [channel, payload] pairs, and periscope splits ONE snapshot across about seventeen messages of 1,024 rows — buffer on (ticker, timestamp) and flush when has_more turns false, or you persist a third of a picture',
  },
];
